# https://github.com/marketplace/actions/hadolint-action
# https://docs.docker.com/ci-cd/github-actions/
# https://github.com/MaastrichtU-IDS/get-started-with-docker/blob/main/.github/workflows/publish-docker.yml
# https://pet2cattle.com/2021/09/build-multiarch-container-github-action
# https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-container-registry

name: Build

env:
  IMAGE_NAME: unbound-alpine

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "Dockerfile"
      - "etc/unbound/unbound.conf"
#  schedule:
#    - cron: "19 7 * * 3"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: hadolint
        uses: hadolint/hadolint-action@v2.1.0

  push:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - name: Image name
        id: imagename
        run: |
          IMAGE_ID=ghcr.io/${{ github.repository_owner }}/$IMAGE_NAME
          # Change all uppercase to lowercase
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
          echo "::set-output name=tags::$IMAGE_ID"
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: all
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          logout: true
      - name: Build image
        uses: docker/build-push-action@v2
        with:
          tags: testimage
          platforms: linux/arm/v7
          cache-to: type=gha,mode=max
          pull: true
          load: true
      - name: Test image
        # https://workbench.sidnlabs.nl/bad-dnssec.html
        run: |
          docker run --name=test --rm --network=host --platform=linux/arm/v7 -d testimage
          sleep 10s
          docker logs test
          docker exec test ls /var/lib/unbound/root.hints
          docker exec test ls /var/lib/unbound/root.key
          docker exec test ls /var/lib/unbound/root.zone
          docker exec test /usr/sbin/unbound-checkconf -f /etc/unbound/unbound.conf
          docker exec test drill -4D -p 8253 ok.ok.ok.bad-dnssec.wb.sidnlabs.nl @127.0.0.1  | tee /dev/stderr | grep -q NOERROR
          docker exec test drill -4D -p 8253 ok.bogussig.ok.bad-dnssec.wb.sidnlabs.nl @127.0.0.1 | tee /dev/stderr | grep -q SERVFAIL
          docker exec test drill -4D -p 8253 signotincepted.bad-dnssec.wb.sidnlabs.nl @127.0.0.1 | tee /dev/stderr | grep -q SERVFAIL
          docker exec test drill -4D -p 8253 ok.ok.sigexpired.bad-dnssec.wb.sidnlabs.nl @127.0.0.1 | tee /dev/stderr | grep -q SERVFAIL
          docker exec test drill -4D -p 8253 ok.ok.ok.bad-dnssec.wb.sidnlabs.nl @127.0.0.1 | tee /dev/stderr | egrep -q 'flags:[a-z ]*ad{1}.*;'
          docker exec test drill -4D -p 8253 unknownalgorithm.ok.ok.bad-dnssec.wb.sidnlabs.nl @127.0.0.1 | tee /dev/stderr | egrep -q 'flags:[a-z ]*ad{0}.*;'
          docker stop test
      - name: Push image
        uses: docker/build-push-action@v2
        with:
          tags: ${{ steps.imagename.outputs.tags }}
          platforms: linux/arm/v7
          cache-from: type=gha
          push: true
